const List<Map<String, dynamic>> allContractions = [
  {"id": 1, "contraction": "ABN", "decode": "Airport Beacon "},
  {"id": 2, "contraction": "ABV", "decode": "Above "},
  {"id": 3, "contraction": "ACC", "decode": "Area Control Center (ARTCC) "},
  {"id": 4, "contraction": "ACCUM", "decode": "Accumulate "},
  {"id": 5, "contraction": "ACFT", "decode": "Aircraft "},
  {"id": 6, "contraction": "ACR", "decode": "Air Carrier "},
  {"id": 7, "contraction": "ACT", "decode": "Active "},
  {"id": 8, "contraction": "ADJ", "decode": "Adjacent "},
  {"id": 9, "contraction": "ADZD", "decode": "Advised "},
  {"id": 10, "contraction": "AFD", "decode": "Airport Facility Directory "},
  {"id": 11, "contraction": "AGL", "decode": "Above Ground Level "},
  {"id": 12, "contraction": "ALS", "decode": "Approach Lighting System "},
  {"id": 13, "contraction": "ALT", "decode": "Altitude "},
  {"id": 14, "contraction": "ALTM", "decode": "Altimeter "},
  {"id": 15, "contraction": "ALTN", "decode": "Alternate "},
  {"id": 16, "contraction": "ALTNLY", "decode": "Alternately "},
  {"id": 17, "contraction": "ALSTG", "decode": "Altimeter Setting "},
  {"id": 18, "contraction": "AMDT", "decode": "Amendment "},
  {"id": 19, "contraction": "AMGR", "decode": "Airport Manager "},
  {
    "id": 20,
    "contraction": "AMOS",
    "decode": "Automatic Meteorological Observing System "
  },
  {"id": 21, "contraction": "AP", "decode": "Airport "},
  {"id": 22, "contraction": "APCH", "decode": "Approach "},
  {"id": 23, "contraction": "AP LGT", "decode": "Airport Lighting "},
  {"id": 24, "contraction": "APP", "decode": "Approach Control "},
  {
    "id": 25,
    "contraction": "ARFF",
    "decode": "Aircraft Rescue and Fire Fighting "
  },
  {"id": 26, "contraction": "ARR", "decode": "Arrive, Arrival "},
  {
    "id": 27,
    "contraction": "ASOS",
    "decode": "Automatic Surface Observing System "
  },
  {"id": 28, "contraction": "ASPH", "decode": "Asphalt "},
  {"id": 29, "contraction": "ATC", "decode": "Air Traffic Control "},
  {
    "id": 30,
    "contraction": "ATCCC",
    "decode": "Air Traffic Control Command Center "
  },
  {
    "id": 31,
    "contraction": "ATIS",
    "decode": "Automatic Terminal Information Service "
  },
  {
    "id": 32,
    "contraction": "AUTOB",
    "decode": "Automatic Weather Reporting System "
  },
  {"id": 33, "contraction": "AUTH", "decode": "Authority "},
  {"id": 34, "contraction": "AVBL", "decode": "Available "},
  {
    "id": 35,
    "contraction": "AWOS",
    "decode": "Automatic Weather Observing/Reporting System "
  },
  {"id": 36, "contraction": "AWY", "decode": "Airway "},
  {"id": 37, "contraction": "AZM", "decode": "Azimuth "},
  {"id": 38, "contraction": "BA FAIR", "decode": "Braking action fair "},
  {"id": 39, "contraction": "BA NIL", "decode": "Braking action nil "},
  {"id": 40, "contraction": "BA POOR", "decode": "Braking action poor "},
  {"id": 41, "contraction": "BC", "decode": "Back Course "},
  {"id": 42, "contraction": "BCN", "decode": "Beacon "},
  {
    "id": 43,
    "contraction": "BERM",
    "decode": "Snowbank(s) Containing Earth/Gravel "
  },
  {"id": 44, "contraction": "BLW", "decode": "Below "},
  {"id": 45, "contraction": "BND", "decode": "Bound "},
  {"id": 46, "contraction": "BRG", "decode": "Bearing "},
  {"id": 47, "contraction": "BYD", "decode": "Beyond "},
  {"id": 48, "contraction": "CAAS", "decode": "Class A Airspace "},
  {"id": 49, "contraction": "CAT", "decode": "Category "},
  {"id": 50, "contraction": "CBAS", "decode": "Class B Airspace "},
  {"id": 51, "contraction": "CBSA", "decode": "Class B Surface Area "},
  {"id": 52, "contraction": "CCAS", "decode": "Class C Airspace "},
  {"id": 53, "contraction": "CCLKWS", "decode": "Counterclockwise "},
  {"id": 54, "contraction": "CCSA", "decode": "Class C Surface Area "},
  {"id": 55, "contraction": "CD", "decode": "Clearance Delivery "},
  {"id": 56, "contraction": "CDAS", "decode": "Class D Airspace "},
  {"id": 57, "contraction": "CDSA", "decode": "Class D Surface Area "},
  {"id": 58, "contraction": "CEAS", "decode": "Class E Airspace "},
  {"id": 59, "contraction": "CESA", "decode": "Class E Surface Area "},
  {"id": 60, "contraction": "CFR", "decode": "Code of Federal Regulations "},
  {"id": 61, "contraction": "CGAS", "decode": "Class G Airspace "},
  {"id": 62, "contraction": "CHAN", "decode": "Channel "},
  {"id": 63, "contraction": "CHG", "decode": "Change or Modification "},
  {"id": 64, "contraction": "CIG", "decode": "Ceiling "},
  {"id": 65, "contraction": "CK", "decode": "Check "},
  {"id": 66, "contraction": "CL", "decode": "Centre Line "},
  {"id": 67, "contraction": "CLKWS", "decode": "Clockwise "},
  {
    "id": 68,
    "contraction": "CLR",
    "decode": "Clearance, Clear(s), Cleared to "
  },
  {"id": 69, "contraction": "CLSD", "decode": "Closed "},
  {"id": 70, "contraction": "CMB", "decode": "Climb "},
  {"id": 71, "contraction": "CMSND", "decode": "Commissioned "},
  {"id": 72, "contraction": "CNL", "decode": "Cancel "},
  {"id": 73, "contraction": "CNTRLN", "decode": "Centerline "},
  {"id": 74, "contraction": "COM", "decode": "Communications "},
  {"id": 75, "contraction": "CONC", "decode": "Concrete "},
  {"id": 76, "contraction": "CPD", "decode": "Coupled "},
  {"id": 77, "contraction": "CRS", "decode": "Course "},
  {"id": 78, "contraction": "CTC", "decode": "Contact "},
  {"id": 79, "contraction": "CTL", "decode": "Control "},
  {"id": 80, "contraction": "DALGT", "decode": "Daylight "},
  {"id": 81, "contraction": "DCMSN", "decode": "Decommission "},
  {"id": 82, "contraction": "DCMSND", "decode": "Decommissioned "},
  {"id": 83, "contraction": "DCT", "decode": "Direct "},
  {"id": 84, "contraction": "DEGS", "decode": "Degrees "},
  {"id": 85, "contraction": "DEP", "decode": "Depart, Departure "},
  {"id": 86, "contraction": "DEP PROC", "decode": "Departure Procedure "},
  {"id": 87, "contraction": "DH", "decode": "Decision Height "},
  {"id": 88, "contraction": "DISABLD", "decode": "Disabled "},
  {"id": 89, "contraction": "DIST", "decode": "Distance "},
  {"id": 90, "contraction": "DLA", "decode": "Delay or Delayed "},
  {"id": 91, "contraction": "DLT", "decode": "Delete "},
  {"id": 92, "contraction": "DLY", "decode": "Daily "},
  {"id": 93, "contraction": "DME", "decode": "Distance Measuring Equipment "},
  {"id": 94, "contraction": "DMSTN", "decode": "Demonstration "},
  {"id": 95, "contraction": "DP", "decode": "Dewpoint Temperature "},
  {
    "id": 96,
    "contraction": "DRFT",
    "decode": "Snowbank/s Caused by Wind Action "
  },
  {"id": 97, "contraction": "DSPLCD", "decode": "Displaced "},
  {"id": 98, "contraction": "E", "decode": "East "},
  {"id": 99, "contraction": "EB", "decode": "Eastbound "},
  {
    "id": 100,
    "contraction": "EFAS",
    "decode": "En Route Flight Advisory Service "
  },
  {"id": 101, "contraction": "ELEV", "decode": "Elevation "},
  {"id": 102, "contraction": "ENG", "decode": "Engine "},
  {"id": 103, "contraction": "ENRT", "decode": "En Route "},
  {"id": 104, "contraction": "ENTR", "decode": "Entire "},
  {"id": 105, "contraction": "EXC", "decode": "Except "},
  {"id": 106, "contraction": "FAC", "decode": "Facility or Facilities "},
  {"id": 107, "contraction": "FAF", "decode": "Final Approach Fix "},
  {"id": 108, "contraction": "FAN MKR", "decode": "Fan Marker "},
  {"id": 109, "contraction": "FDC", "decode": "Flight Data Center "},
  {"id": 110, "contraction": "FI/T", "decode": "Flight Inspection Temporary "},
  {"id": 111, "contraction": "FI/P", "decode": "Flight Inspection Permanent "},
  {"id": 112, "contraction": "FM", "decode": "From "},
  {"id": 113, "contraction": "FNA", "decode": "Final Approach "},
  {"id": 114, "contraction": "FPM", "decode": "Feet Per Minute "},
  {"id": 115, "contraction": "FREQ", "decode": "Frequency "},
  {"id": 116, "contraction": "FRH", "decode": "Fly Runway Heading "},
  {"id": 117, "contraction": "FRI", "decode": "Friday "},
  {"id": 118, "contraction": "FRZN", "decode": "Frozen "},
  {
    "id": 119,
    "contraction": "FSS",
    "decode": "Automated/Flight Service Station "
  },
  {"id": 120, "contraction": "FT", "decode": "Foot, Feet "},
  {"id": 121, "contraction": "GC", "decode": "Ground Control "},
  {"id": 122, "contraction": "GCA", "decode": "Ground Control Approach "},
  {"id": 123, "contraction": "GCO", "decode": "Ground Communications Outlet "},
  {"id": 124, "contraction": "GOVT", "decode": "Government "},
  {"id": 125, "contraction": "GP", "decode": "Glide Path "},
  {"id": 126, "contraction": "GPS", "decode": "Global Positioning System "},
  {"id": 127, "contraction": "GRVL", "decode": "Gravel "},
  {"id": 128, "contraction": "HAA", "decode": "Height Above Airport "},
  {"id": 129, "contraction": "HAT", "decode": "Height Above Touchdown "},
  {"id": 130, "contraction": "HDG", "decode": "Heading "},
  {"id": 131, "contraction": "HEL", "decode": "Helicopter "},
  {"id": 132, "contraction": "HELI", "decode": "Heliport "},
  {"id": 133, "contraction": "HIRL", "decode": "High Intensity Runway Lights "},
  {
    "id": 134,
    "contraction": "HIWAS",
    "decode": "Hazardous Inflight Weather Advisory Service "
  },
  {"id": 135, "contraction": "HLDG", "decode": "Holding "},
  {"id": 136, "contraction": "HOL", "decode": "Holiday "},
  {"id": 137, "contraction": "HP", "decode": "Holding Pattern "},
  {"id": 138, "contraction": "HR", "decode": "Hour "},
  {"id": 139, "contraction": "IAF", "decode": "Initial Approach Fix "},
  {"id": 140, "contraction": "IAP", "decode": "Instrument Approach Procedure "},
  {"id": 141, "contraction": "INBD", "decode": "Inbound "},
  {"id": 142, "contraction": "ID", "decode": "Identification "},
  {
    "id": 143,
    "contraction": "IDENT",
    "decode": "Identify, Identifier, Identification "
  },
  {"id": 144, "contraction": "IF", "decode": "Intermediate Fix "},
  {"id": 145, "contraction": "ILS", "decode": "Instrument Landing System "},
  {"id": 146, "contraction": "IM", "decode": "Inner Marker "},
  {
    "id": 147,
    "contraction": "IMC",
    "decode": "Instrument Meteorological Conditions "
  },
  {"id": 148, "contraction": "IN", "decode": "Inch, Inches "},
  {"id": 149, "contraction": "INDEFLY", "decode": "Indefinitely "},
  {"id": 150, "contraction": "INFO", "decode": "Information "},
  {"id": 151, "contraction": "INOP", "decode": "Inoperative "},
  {"id": 152, "contraction": "INSTR", "decode": "Instrument "},
  {"id": 153, "contraction": "INT", "decode": "Intersection "},
  {"id": 154, "contraction": "INTL", "decode": "International "},
  {"id": 155, "contraction": "INTST", "decode": "Intensity "},
  {"id": 156, "contraction": "IR", "decode": "Ice On Runway(s) "},
  {"id": 157, "contraction": "KT", "decode": "Knots "},
  {"id": 158, "contraction": "L", "decode": "Left "},
  {"id": 159, "contraction": "LAA", "decode": "Local Airport Advisory "},
  {"id": 160, "contraction": "LAT", "decode": "Latitude "},
  {
    "id": 161,
    "contraction": "LAWRS",
    "decode": "Limited Aviation Weather Reporting Station "
  },
  {"id": 162, "contraction": "LB", "decode": "Pound(s) "},
  {"id": 163, "contraction": "LC", "decode": "Local Control "},
  {"id": 164, "contraction": "LOC", "decode": "Local, Locally, Location "},
  {"id": 165, "contraction": "LCTD", "decode": "Located "},
  {
    "id": 166,
    "contraction": "LDA",
    "decode": "Localizer Type Directional Aid "
  },
  {"id": 167, "contraction": "LGT", "decode": "Light or Lighting "},
  {"id": 168, "contraction": "LGTD", "decode": "Lighted "},
  {"id": 169, "contraction": "LIRL", "decode": "Low Intensity Runway Lights "},
  {
    "id": 134,
    "contraction": "HIWAS",
    "decode": "Hazardous Inflight Weather Advisory"
  },
  {"id": 135, "contraction": "HLDG", "decode": "Holding "},
  {"id": 136, "contraction": "HPA", "decode": "Hectopascal "},
  {"id": 137, "contraction": "HR", "decode": "Hour "},
  {"id": 138, "contraction": "HS", "decode": "Hot Spot "},
  {"id": 139, "contraction": "HUD", "decode": "Head-Up Display "},
  {"id": 140, "contraction": "HVY", "decode": "Heavy "},
  {"id": 141, "contraction": "HWY", "decode": "Highway "},
  {"id": 142, "contraction": "HZ", "decode": "Haze "},
  {"id": 143, "contraction": "IAF", "decode": "Initial Approach Fix "},
  {"id": 144, "contraction": "IAS", "decode": "Indicated Airspeed "},
  {
    "id": 145,
    "contraction": "",
    "decode": "International Civil Aviation Organization"
  },
  {"id": 146, "contraction": "ID", "decode": "Identifier "},
  {"id": 147, "contraction": "IF", "decode": "Intermediate Fix "},
  {"id": 148, "contraction": "IFR", "decode": "Instrument Flight Rules "},
  {"id": 149, "contraction": "ILS", "decode": "Instrument Landing System "},
  {"id": 150, "contraction": "IM", "decode": "Inner Marker "},
  {
    "id": 151,
    "contraction": "IMC",
    "decode": "Instrument Meteorological Conditions "
  },
  {"id": 152, "contraction": "INBD", "decode": "Inbound "},
  {"id": 153, "contraction": "INOP", "decode": "Inoperative "},
  {"id": 154, "contraction": "INT", "decode": "Intersection "},
  {"id": 155, "contraction": "INTL", "decode": "International "},
  {"id": 156, "contraction": "IR", "decode": "Ice on Runway "},
  {
    "id": 157,
    "contraction": "ISA",
    "decode": "International Standard Atmosphere "
  },
  {"id": 158, "contraction": "ISOL", "decode": "Isolated "},
  {"id": 159, "contraction": "KT", "decode": "Knot "},
  {"id": 160, "contraction": "L", "decode": "Left "},
  {"id": 161, "contraction": "LAT", "decode": "Latitude "},
  {"id": 162, "contraction": "LDA", "decode": "Landing Distance Available "},
  {"id": 163, "contraction": "LDG", "decode": "Landing "},
  {"id": 164, "contraction": "LEN", "decode": "Length "},
  {"id": 165, "contraction": "LF", "decode": "Low Frequency "},
  {"id": 166, "contraction": "LGT", "decode": "Light "},
  {"id": 167, "contraction": "LLZ", "decode": "Localizer "},
  {"id": 168, "contraction": "LOC", "decode": "Location "},
  {"id": 169, "contraction": "LONG", "decode": "Longitude "},
  {"id": 170, "contraction": "LTD", "decode": "Limited "},
  {"id": 171, "contraction": "LVL", "decode": "Level "},
  {"id": 172, "contraction": "M", "decode": "Mach Number "},
  {"id": 173, "contraction": "MA", "decode": "Missed Approach "},
  {"id": 174, "contraction": "MAG", "decode": "Magnetic "},
  {"id": 175, "contraction": "MAP", "decode": "Missed Approach Point "},
  {"id": 176, "contraction": "MCA", "decode": "Minimum Crossing Altitude "},
  {"id": 177, "contraction": "MDA", "decode": "Minimum Descent Altitude "},
  {"id": 178, "contraction": "MEA", "decode": "Minimum Enroute Altitude "},
  {"id": 179, "contraction": "MET", "decode": "Meteorological "},
  {"id": 180, "contraction": "MHA", "decode": "Minimum Holding Altitude "},
  {"id": 181, "contraction": "MHZ", "decode": "Megahertz "},
  {"id": 182, "contraction": "MIN", "decode": "Minute "},
  {"id": 183, "contraction": "MKR", "decode": "Marker "},
  {"id": 184, "contraction": "MLS", "decode": "Microwave Landing System "},
  {
    "id": 185,
    "contraction": "MNPS",
    "decode": "Minimum Navigation Performance Specification "
  },
  {
    "id": 186,
    "contraction": "MOCA",
    "decode": "Minimum Obstruction Clearance Altitude "
  },
  {"id": 187, "contraction": "MORA", "decode": "Minimum Off-Route Altitude "},
  {"id": 188, "contraction": "MSA", "decode": "Minimum Safe Altitude "},
  {"id": 189, "contraction": "MSL", "decode": "Mean Sea Level "},
  {"id": 190, "contraction": "MTOW", "decode": "Maximum Takeoff Weight "},
  {"id": 191, "contraction": "N", "decode": "North "},
  {"id": 192, "contraction": "NDB", "decode": "Non-Directional Beacon "},
  {"id": 193, "contraction": "NM", "decode": "Nautical Mile "},
  {"id": 194, "contraction": "NOF", "decode": "International NOTAM Office "},
  {"id": 195, "contraction": "NOTAM", "decode": "Notice to Airmen "},
  {"id": 196, "contraction": "NPA", "decode": "Non-Precision Approach "},
  {"id": 197, "contraction": "NR", "decode": "Number "},
  {"id": 198, "contraction": "NW", "decode": "Northwest "},
  {"id": 199, "contraction": "OAC", "decode": "Oceanic Area Control "},
  {"id": 200, "contraction": "OCA", "decode": "Oceanic Control Area "},
  {"id": 201, "contraction": "OCH", "decode": "Obstacle Clearance Height "},
  {"id": 202, "contraction": "OCL", "decode": "Obstacle Clearance Limit "},
  {
    "id": 203,
    "contraction": "OIS",
    "decode": "Obstacle Identification Surface "
  },
  {"id": 204, "contraction": "OM", "decode": "Outer Marker "},
  {"id": 205, "contraction": "OPR", "decode": "Operator "},
  {"id": 206, "contraction": "OPS", "decode": "Operations "},
  {"id": 207, "contraction": "PA", "decode": "Precision Approach "},
  {
    "id": 208,
    "contraction": "PAPI",
    "decode": "Precision Approach Path Indicator "
  },
  {"id": 209, "contraction": "PAR", "decode": "Precision Approach Radar "},
  {"id": 210, "contraction": "PAX", "decode": "Passengers "},
  {
    "id": 211,
    "contraction": "PCN",
    "decode": "Pavement Classification Number "
  },
  {"id": 212, "contraction": "PIREP", "decode": "Pilot Report "},
  {"id": 213, "contraction": "PLN", "decode": "Flight Plan "},
  {"id": 214, "contraction": "PMSV", "decode": "Pilot-to-Metro Service "},
  {"id": 215, "contraction": "PNR", "decode": "Point of No Return "},
  {"id": 216, "contraction": "POB", "decode": "Persons on Board "},
  {"id": 217, "contraction": "PPR", "decode": "Prior Permission Required "},
  {"id": 218, "contraction": "PSR", "decode": "Primary Surveillance Radar "},
  {"id": 219, "contraction": "PT", "decode": "Procedure Turn "},
  {"id": 220, "contraction": "PWR", "decode": "Power "},
  {
    "id": 221,
    "contraction": "QFE",
    "decode": "Atmospheric Pressure at Aerodrome Elevation "
  },
  {
    "id": 222,
    "contraction": "QNH",
    "decode": "Altimeter Sub-Scale Setting to Obtain Elevation "
  },
  {"id": 223, "contraction": "R", "decode": "Right "},
  {"id": 224, "contraction": "RA", "decode": "Resolution Advisory "},
  {"id": 225, "contraction": "RAG", "decode": "Runway Arresting Gear "},
  {"id": 226, "contraction": "RCC", "decode": "Rescue Coordination Center "},
  {"id": 227, "contraction": "RCL", "decode": "Runway Center Line "},
  {"id": 228, "contraction": "RCLL", "decode": "Runway Center Line Lights "},
  {"id": 229, "contraction": "RDL", "decode": "Radial "},
  {"id": 230, "contraction": "REC", "decode": "Receive "},
  {"id": 231, "contraction": "REDL", "decode": "Runway Edge Light "},
  {"id": 232, "contraction": "REF", "decode": "Reference "},
  {"id": 233, "contraction": "REQ", "decode": "Request "},
  {"id": 234, "contraction": "RMI", "decode": "Radio Magnetic Indicator "},
  {"id": 235, "contraction": "RNAV", "decode": "Area Navigation "},
  {
    "id": 236,
    "contraction": "RNP",
    "decode": "Required Navigation Performance "
  },
  {"id": 237, "contraction": "ROC", "decode": "Rate of Climb "},
  {"id": 238, "contraction": "ROD", "decode": "Rate of Descent "},
  {"id": 239, "contraction": "RPI", "decode": "Runway Point of Intercept "},
  {"id": 240, "contraction": "RPL", "decode": "Repetitive Flight Plan "},
  {"id": 241, "contraction": "RSC", "decode": "Runway Surface Condition "},
  {"id": 242, "contraction": "RSR", "decode": "En Route Surveillance Radar "},
  {"id": 243, "contraction": "RTF", "decode": "Radiotelephony "},
  {"id": 244, "contraction": "RTG", "decode": "Radiotelegraph "},
  {"id": 245, "contraction": "RTS", "decode": "Return to Service "},
  {"id": 246, "contraction": "RTT", "decode": "Radioteletype "},
  {"id": 247, "contraction": "RTZL", "decode": "Runway Touchdown Zone Lights "},
  {"id": 248, "contraction": "RV", "decode": "Rescue Vehicle "},
  {
    "id": 249,
    "contraction": "RVSM",
    "decode": "Reduced Vertical Separation Minimum "
  },
  {"id": 250, "contraction": "RWY", "decode": "Runway "},
  {
    "id": 251,
    "contraction": "SALS",
    "decode": "Short Approach Lighting System "
  },
  {"id": 252, "contraction": "SAR", "decode": "Search and Rescue "},
  {
    "id": 253,
    "contraction": "SAS",
    "decode": "Stabilizer Augmentation System "
  },
  {"id": 254, "contraction": "SAT", "decode": "Saturday "},
  {
    "id": 255,
    "contraction": "SBAS",
    "decode": "Satellite-Based Augmentation System "
  },
  {
    "id": 256,
    "contraction": "SDF",
    "decode": "Simplified Directional Facility "
  },
  {"id": 257, "contraction": "SE", "decode": "South East "},
  {"id": 258, "contraction": "SEC", "decode": "Second "},
  {"id": 259, "contraction": "SELCAL", "decode": "Selective Calling System "},
  {"id": 260, "contraction": "SID", "decode": "Standard Instrument Departure "},
  {
    "id": 261,
    "contraction": "SIF",
    "decode": "Selective Identification Feature "
  },
  {
    "id": 262,
    "contraction": "SIGMET",
    "decode": "Significant Meteorological Information "
  },
  {"id": 263, "contraction": "SIMUL", "decode": "Simultaneous "},
  {"id": 264, "contraction": "SITREP", "decode": "Situation Report "},
  {"id": 265, "contraction": "SKED", "decode": "Scheduled "},
  {"id": 266, "contraction": "SLP", "decode": "Sea Level Pressure "},
  {"id": 267, "contraction": "SMC", "decode": "Surface Movement Control "},
  {"id": 268, "contraction": "SMR", "decode": "Surface Movement Radar "},
  {
    "id": 269,
    "contraction": "SNOCLO",
    "decode": "Aerodrome Closed Due to Snow "
  },
  {"id": 270, "contraction": "SPECI", "decode": "Special Weather Report "},
  {"id": 271, "contraction": "SR", "decode": "Sunrise "},
  {"id": 272, "contraction": "SRA", "decode": "Surveillance Radar Approach "},
  {"id": 273, "contraction": "SRY", "decode": "Secondary "},
  {"id": 274, "contraction": "SS", "decode": "Sunset "},
  {"id": 275, "contraction": "SSR", "decode": "Secondary Surveillance Radar "},
  {
    "id": 276,
    "contraction": "STAR",
    "decode": "Standard Terminal Arrival Route "
  },
  {"id": 277, "contraction": "STD", "decode": "Standard "},
  {"id": 278, "contraction": "STN", "decode": "Station "},
  {"id": 279, "contraction": "STOL", "decode": "Short Takeoff and Landing "},
  {"id": 280, "contraction": "STS", "decode": "Status "},
  {"id": 281, "contraction": "SUP", "decode": "Supplement "},
  {"id": 282, "contraction": "SVC", "decode": "Service "},
  {"id": 283, "contraction": "SW", "decode": "South West "},
  {"id": 284, "contraction": "TAF", "decode": "Terminal Aerodrome Forecast "},
  {"id": 285, "contraction": "TAS", "decode": "True Airspeed "},
  {"id": 286, "contraction": "TAX", "decode": "Taxi "},
  {"id": 287, "contraction": "TCH", "decode": "Threshold Crossing Height "},
  {"id": 288, "contraction": "TDZ", "decode": "Touchdown Zone "},
  {"id": 289, "contraction": "TEMPO", "decode": "Temporary "},
  {"id": 290, "contraction": "TFC", "decode": "Traffic "},
  {"id": 291, "contraction": "TGL", "decode": "Touch and Go Landing "},
  {"id": 292, "contraction": "THR", "decode": "Threshold "},
  {"id": 293, "contraction": "TKOF", "decode": "Takeoff "},
  {"id": 294, "contraction": "TL", "decode": "Turn Left "},
  {"id": 295, "contraction": "TMA", "decode": "Terminal Control Area "},
  {"id": 296, "contraction": "TNA", "decode": "Turn Altitude "},
  {"id": 297, "contraction": "TOC", "decode": "Top of Climb "},
  {"id": 298, "contraction": "TOD", "decode": "Top of Descent "},
  {"id": 299, "contraction": "TORA", "decode": "Takeoff Run Available "},
  {"id": 300, "contraction": "TP", "decode": "Turning Point "},
  {"id": 301, "contraction": "TR", "decode": "Track "},
  {"id": 302, "contraction": "TWR", "decode": "Tower "},
  {"id": 303, "contraction": "TWY", "decode": "Taxiway "},
  {"id": 304, "contraction": "UHF", "decode": "Ultra High Frequency "},
  {"id": 305, "contraction": "UIC", "decode": "Upper Information Center "},
  {"id": 306, "contraction": "ULR", "decode": "Ultra Long Range "},
  {"id": 307, "contraction": "UNL", "decode": "Unlimited "},
  {"id": 308, "contraction": "U/S", "decode": "Unserviceable "},
  {"id": 309, "contraction": "UTA", "decode": "Upper Control Area "},
  {"id": 310, "contraction": "UTC", "decode": "Coordinated Universal Time "},
  {"id": 311, "contraction": "VAC", "decode": "Visual Approach Chart "},
  {
    "id": 312,
    "contraction": "VASI",
    "decode": "Visual Approach Slope Indicator "
  },
  {
    "id": 313,
    "contraction": "VDF",
    "decode": "Very High Frequency Direction Finding "
  },
  {"id": 314, "contraction": "VFR", "decode": "Visual Flight Rules "},
  {"id": 315, "contraction": "VHF", "decode": "Very High Frequency "},
  {"id": 316, "contraction": "VIP", "decode": "Very Important Person "},
  {"id": 317, "contraction": "VIS", "decode": "Visibility "},
  {
    "id": 318,
    "contraction": "VMC",
    "decode": "Visual Meteorological Conditions "
  },
  {
    "id": 319,
    "contraction": "VOLMET",
    "decode": "Meteorological Information for Aircraft in Flight "
  },
  {
    "id": 320,
    "contraction": "VOR",
    "decode": "Very High Frequency Omnidirectional Range "
  },
  {"id": 321, "contraction": "VORTAC", "decode": "VOR and TACAN Combination "},
  {"id": 322, "contraction": "VRB", "decode": "Variable "},
  {"id": 323, "contraction": "VSA", "decode": "Visual Segment Approach "},
  {"id": 324, "contraction": "W", "decode": "West "},
  {
    "id": 325,
    "contraction": "WAAS",
    "decode": "Wide Area Augmentation System "
  },
  {"id": 326, "contraction": "WDI", "decode": "Wind Direction Indicator "},
  {"id": 327, "contraction": "WED", "decode": "Wednesday "},
  {"id": 328, "contraction": "WGS", "decode": "World Geodetic System "},
  {"id": 329, "contraction": "WI", "decode": "Within "},
  {"id": 330, "contraction": "WIP", "decode": "Work in Progress "},
  {"id": 331, "contraction": "WPT", "decode": "Waypoint "},
  {"id": 332, "contraction": "WX", "decode": "Weather "},
  {"id": 333, "contraction": "X", "decode": "Cross "},
  {"id": 334, "contraction": "XNG", "decode": "Crossing "},
  {"id": 335, "contraction": "Y", "decode": "Yellow "},
  {"id": 336, "contraction": "Z", "decode": "Zulu Time "}
];
